name: MuleSoft CloudHub 2.0 Deployment

on:
  workflow_dispatch: #  Allowing manual branch execution

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
          
      - name: Set up JDK 17 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test Phase
        if: github.ref == 'refs/heads/develop'
        run:  mvn clean test -s .maven/settings.xml -Dmule.env=${{ vars.MULE_ENV_DEV }} 
 #        -Dmule.key=${{ secrets.ENCRYPTION_KEY_DEV }}

      - name: Package Phase
        run:  mvn clean package -DskipTests -s .maven/settings.xml -Danypoint.username=${{ secrets.ANYPOINT_USERNAME }} -Danypoint.password=${{ secrets.ANYPOINT_PASSWORD }}

      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
          mv $artifactName1 $artifactName2
          
      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: .
          include-hidden-files: true

  Deploy_To_Dev:
    needs: CI
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: DEV
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}
      BUSINESS_GROUP_ID: ${{ secrets.BUSINESS_GROUP_ID }}
      MULEENV: ${{ vars.MULE_ENV }}
      CLOUDHUBENV: ${{vars.CLOUDHUB_ENV}}
      CLOUDHUB_REGION: ${{vars.TARGET}}
      PROVIDER: ${{vars.PROVIDER}}
      REPLICAS: ${{vars.REPLICAS}}
    
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Set up JDK 17 & Maven Cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Publish to Exchange
        run: |
          muleDeployableJar=$(ls *.jar | head -1)

          mvn deploy \
          -DskipTests \
          -s .maven/settings.xml \
          -Dmule.artifact="$muleDeployableJar"

      - name: Deploy To Development
        run: |
          mvn mule:deploy -DskipTests -s .maven/settings.xml -DskipTests -DskipDeploymentVerification="true"
          mvn mule:deploy  -DskipTests -Dmule.version=$MULEVERSION\
            -Danypoint.businessGroupId=$BUSINESS_GROUP_ID -Dprovider=$PROVIDER\
            -Dcloudhub.env=$CLOUDHUB_ENV -Dcoudhub.workerType=MICRO\
            -Dcloudhub.region=$CLOUDHUB_REGION -Dreplicas=$REPLICAS\
            -DconnectedApp_clientId=$CA_CLIENT_ID\
            -DconnectedApp_clientSecret=$CA_CLIENT_SECRET



  Deploy_To_QA:
    needs: CI
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: drop

      - name: Set up JDK 17 & Maven Cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Publish to Exchange
        run: |
          mvn deploy -DskipTests -s .maven/settings.xml -Dmule.artifact=$artifactName

      - name: Deploy To QA
        run: |
          mvn mule:deploy -DskipTests -s .maven/settings.xml -DskipTests -DskipDeploymentVerification="true"

  Deploy_To_UAT:
    needs: CI
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: drop

      - name: Set up JDK 17 & Maven Cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Publish to Exchange
        run: |
          mvn deploy -DskipTests -s .maven/settings.xml -Dmule.artifact=$artifactName

      - name: Deploy To UAT
        run: |
          mvn mule:deploy -DskipTests -s .maven/settings.xml -DskipTests -DskipDeploymentVerification="true"

  Deploy_To_PROD:
    needs: CI
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: drop

      - name: Set up JDK 17 & Maven Cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Publish to Exchange
        run: |
          mvn deploy -DskipTests -s .maven/settings.xml -Dmule.artifact=$artifactName

      - name: Deploy To PROD
        run: |
          mvn mule:deploy -DskipTests -s .maven/settings.xml -DskipTests -DskipDeploymentVerification="true"
